=== VoViet266/xml/Buoi_03/bai_2.3/donhang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="quantity" type="xs:int" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required" />
                    </xs:complexType>
                    <!-- "@" dùng để tham chiếu đến thuộc tính, nếu không có @ thì sẽ hiển là 1 phần
                    tử con -->
                    <xs:unique name="uniqueProductID">
                        <xs:selector xpath="product" />
                        <xs:field xpath="@id" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueOrderID">
            <xs:selector xpath="order" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>

</xs:schema>

=== VoViet266/xml/buoi_02/bai_2/bai_1.3/donhang.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE store SYSTEM "donhang.dtd"> -->

<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Buoi_03/bai_2.3/donhang.xsd">
    <order id="O001">

        <product id="P001">
            <name>Kem tron Thai Lan</name>
            <quantity>10</quantity>
        </product>
        <product id="P002">
            <name>Kem chong nang</name>
            <quantity>15</quantity>
        </product>

    </order>

    <order id="O002">

        <product id="P003">
            <name>Mit say</name>
            <quantity>25</quantity>
        </product>
        <product id="P004">
            <name>Banh Oreo</name>
            <quantity>20</quantity>
        </product>

    </order>
</store>
